import {StyleSheet} from 'react-native';

export default styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#FFFFFF',
      padding: 5,
    },
    headerText: {
      color: '#2D3142',
      fontSize: 24,
      fontWeight: 600,
      padding: 12,
    },
    deviceCard: {
      borderWidth: 0,
      borderRadius: 7,
      padding: 20,
      margin: 12,
      backgroundColor: '#4F5D75',
    },
    deviceText: {
      color: '#EF8354',
      fontSize: 20,
      fontWeight: 400,
    },
    timeText: {
      color: '#2E3840',
      fontSize: 20,
      fontWeight: 400,
    },
    deviceDetails: {
      color: '#BFC0C0',
      fontSize: 13,
      fontWeight: 300,
    },
    logTextStyle: {
      color: '#4E6E81',
      fontSize: 15,
    },
    noDevicesTextStyle: {
      color: '#2D3142',
      fontSize: 18,
      padding: 20,
    },
    buttonStyle: {
      borderWidth: 0,
      borderRadius: 5,
      padding: 17,
      margin: 7,
      backgroundColor: '#2E3840',
      color: '#ECF2FF',
      textAlign: 'center',
      fontSize: 20,
    },
    disabledButtonStyle: {
      backgroundColor: '#15142d',
      color: '#919191',
    },
    modalButton: {
      borderWidth: 0,
      borderRadius: 5,
      padding: 10,
      margin: 5,
      backgroundColor: '#2E3840',
      color: '#ECF2FF',
      textAlign: 'center',
      fontSize: 17,
    },
    modalView: {
      margin: 20,
      marginTop: 70,
      backgroundColor: '#EFEFEF',
      borderRadius: 20,
      borderWidth: 1,
      borderColor: '#DBE1EE',
      padding: 20,
      shadowColor: '#000',
      shadowOpacity: 0.25,
      shadowRadius: 2,
      elevation: 3,
      color: '#000',
    },
    modalHeader: {
      color: '#2D3142',
      fontSize: 20,
      fontWeight: 500,
      padding: 10,
      textAlign: 'center',
    },
    modalText: {
      color: '#2D3142',
      backgroundColor: '#FFFFFF',
      padding: 10,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: '#2D314211',
      margin: 5,
    },
  });